name: simple-build
on: [push]
jobs:
  simple-build:
    runs-on: macos-11
    steps:
        - uses: actions/checkout@v2
        - run: git checkout 
        - name: Set up JDK 11
          uses: actions/setup-java@v2
          with:
            java-version: '11'
            distribution: 'adopt'
        - name: Build with Maven 
          run: mvn clean verify 

